### ISSUE TITLE
Itemsadder is broken

### ISSUE THREAD

**Issue by addpromax** [InfernalSuite/AdvancedSlimePaper#117]
**Describe the issue**
Itemadder is broken
**Spigot version**
AdvancedSlimePaper version 1.20.6-16042-HEAD@b5c967a
**Plugin version**
ItemsAdder 4.0.1-alpha-test-3
plugin-3.0.0-SNAPSHOT
**How to reproduce**
Install itemsadder v4 - alpha 3
Not work in server
**Crash reports (if available)**
[18:34:13] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v4.0.1-alpha-test-3
[18:34:14] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 4.0.1-alpha-test-3
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.54
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     AdvancedSlimePaper 1.20.6-16042-b5c967a (MC: 1.20.6)
                                               
[18:34:14] [Server thread/WARN]: [ItemsAdder]  
[18:34:14] [Server thread/WARN]: [ItemsAdder] This is a test version of ItemsAdder v4 for Minecraft 1.20.6+.
[18:34:14] [Server thread/WARN]: [ItemsAdder] Please make backups before using this version.
[18:34:14] [Server thread/WARN]: [ItemsAdder] Use this only on a test server.
[18:34:14] [Server thread/WARN]: [ItemsAdder] I am not responsible for any damage done to your server.
[18:34:14] [Server thread/WARN]: [ItemsAdder]  
[18:34:14] [Server thread/INFO]: [ItemsAdder] Registered Skript API
[18:34:14] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v4.0.1-alpha-test-3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/infernalsuite/aswm/api/SlimePlugin
	at ItemsAdder_4.0.1-alpha-test-3.jar/dev.lone.itemsadder.Core.OtherPlugins.AdvancedSlimePaperWrapper.<init>(SourceFile:21) ~[ItemsAdder_4.0.1-alpha-test-3.jar:?]
	at ItemsAdder_4.0.1-alpha-test-3.jar/dev.lone.itemsadder.Core.OtherPlugins.AdvancedSlimePaperWrapper.init(SourceFile:16) ~[ItemsAdder_4.0.1-alpha-test-3.jar:?]
	at ItemsAdder_4.0.1-alpha-test-3.jar/dev.lone.itemsadder.Main.onEnable(SourceFile:385) ~[ItemsAdder_4.0.1-alpha-test-3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[slimeworldmanager-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[slimeworldmanager-1.20.6.jar:1.20.6-16042-b5c967a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[slimeworldmanager-1.20.6.jar:1.20.6-16042-b5c967a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[slimeworldmanager-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:605) ~[slimeworldmanager-1.20.6.jar:1.20.6-16042-b5c967a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:554) ~[slimeworldmanager-1.20.6.jar:1.20.6-16042-b5c967a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:693) ~[slimeworldmanager-1.20.6.jar:1.20.6-16042-b5c967a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[slimeworldmanager-1.20.6.jar:1.20.6-16042-b5c967a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[slimeworldmanager-1.20.6.jar:1.20.6-16042-b5c967a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154) ~[slimeworldmanager-1.20.6.jar:1.20.6-16042-b5c967a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[slimeworldmanager-1.20.6.jar:1.20.6-16042-b5c967a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.infernalsuite.aswm.api.SlimePlugin
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[slimeworldmanager-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[slimeworldmanager-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 15 more
[18:34:14] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v4.0.1-alpha-test-3

**Comment by kyngs** [comment]
The api-rework branch is not supported nor intended to be used, why are you using it? Obviously, the branch reworks the API, making old plugins incompatible.

**Comment by addpromax** [comment]
sorry I find question
