### ISSUE TITLE
World PDC doesn't work with byte array

### ISSUE THREAD

**Issue by GliczDev** [InfernalSuite/AdvancedSlimePaper#120]
**Describe the issue**
I'm using [mfnalex/MorePersistentDataTypes](https://github.com/mfnalex/MorePersistentDataTypes) `DataType.UUID` (which stores byte array) and it throws an exception when trying to read it after world load.
**Spigot version**
1.20.6
**Plugin version**
`SlimeWorldManager version 2.10.0`, latest develop build
**How to reproduce**
Store value with type `DataType.UUID`, unload the world and try to read this value on world load.
**Crash reports (if available)**
```
java.lang.IllegalArgumentException: The found tag instance (IntTag) cannot store byte[]
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:445) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.persistence.CraftPersistentDataTypeRegistry.extract(CraftPersistentDataTypeRegistry.java:348) ~[slimeworldmanager-1.20.6.jar:1.20.6-DEV-118ef07]
        at org.bukkit.craftbukkit.persistence.CraftPersistentDataContainer.get(CraftPersistentDataContainer.java:74) ~[slimeworldmanager-1.20.6.jar:1.20.6-DEV-118ef07]
        at RoxyItems-1.0-SNAPSHOT.jar/net.roxymc.items.furniture.Furniture.lambda$getCustomData$6(Furniture.java:163) ~[RoxyItems-1.0-SNAPSHOT.jar:?]
        at RoxyItems-1.0-SNAPSHOT.jar/net.roxymc.items.furniture.Furniture.lambda$editData$0(Furniture.java:83) ~[RoxyItems-1.0-SNAPSHOT.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
```

**Comment by kyngs** [comment]
Send your code

**Comment by GliczDev** [comment]
Unfortunately my code is a little bit complex, but simplified it's just 
```java
bukkitWorld.getPersistentDataContainer().set(key, DataType.UUID, player.getUniqueId());
```
and
```java
@EventHandler
public void onWorldLoad(WorldLoadEvent e) {
    UUID player = e.getWorld().getPersistentDataContainer(key, DataType.UUID);
}
```
and it works for every other data type I tested (e.g. integer or data container list)

**Comment by kyngs** [comment]
Please provide a plugin that can reproduce this behavior on the latest version

**Comment by kyngs** [comment]
Stale, can't repro
