### ISSUE TITLE
Changing drivers make the plugin failed to find some of them

### ISSUE THREAD

**Issue by Elikill58** [InfernalSuite/AdvancedSlimePaper#129]
**Describe the issue**
If you change driver, the plugin failed to find them.

**Spigot version**
1.21.1

**Plugin version**
3.0.0

**How to reproduce**
I made my own driver which is up to date. To prevent plugin to use olds one, I unregister others.

Here is my code:
```java
private static void manageDrivers() throws SQLException {
	Enumeration<java.sql.Driver> drivers = DriverManager.getDrivers();
	boolean hasOwn = false;
        String packagePrefix = "my.package.prefix";
	while(drivers.hasMoreElements()) {
		java.sql.Driver d = drivers.nextElement();
		String name = d.getClass().getName();
		if(name.contains(packagePrefix)) {
			hasOwn = true;
		} else {
			DriverManager.deregisterDriver(d); // the line that create issue
			Adapter.getAdapter().getLogger().info("Driver " + d.getClass().getName() + " removed.");
		}
	}
	if(!hasOwn) { // if my own isn't already managed
		try {
			Class.forName(packagePrefix + ".cj.jdbc.Driver"); // my own driver
			Adapter.getAdapter().getLogger().info("Registered own driver...");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```
But this create issue with your plugin. It leads to this error:
```
[SlimeWorldPlugin] Error initializing plugin 'plugin-3.0.0.jar' in folder 'plugins' (Is it up to date?)
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://ip:3306/dbname?autoReconnect=true&allowMultiQueries=true&useSSL=false
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.hikari.util.DriverDataSource.<init>(DriverDataSource.java:113) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:327) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.hikari.pool.PoolBase.<init>(PoolBase.java:113) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.hikari.pool.HikariPool.<init>(HikariPool.java:91) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.hikari.HikariDataSource.<init>(HikariDataSource.java:80) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.infernalsuite.aswm.loaders.mysql.MysqlLoader.<init>(MysqlLoader.java:67) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.infernalsuite.aswm.plugin.loader.LoaderManager.<init>(LoaderManager.java:44) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.infernalsuite.aswm.plugin.SWPlugin.onLoad(SWPlugin.java:49) ~[plugin-3.0.0.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[slimeworldmanager-1.21.1.jar:1.21.1-16281-07c3fcc]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[slimeworldmanager-1.21.1.jar:1.21.1-16281-07c3fcc]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:48) ~[slimeworldmanager-1.21.1.jar:1.21.1-16281-07c3fcc]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[slimeworldmanager-1.21.1.jar:1.21.1-16281-07c3fcc]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:547) ~[slimeworldmanager-1.21.1.jar:1.21.1-16281-07c3fcc]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[slimeworldmanager-1.21.1.jar:1.21.1-16281-07c3fcc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[slimeworldmanager-1.21.1.jar:1.21.1-16281-07c3fcc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[slimeworldmanager-1.21.1.jar:1.21.1-16281-07c3fcc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.sql.SQLException: No suitable driver
        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:300) ~[java.sql:?]
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.hikari.util.DriverDataSource.<init>(DriverDataSource.java:105) ~[plugin-3.0.0.jar:?]
        ... 16 more
```
Even if my plugin is loaded before you're own.

**Comment by kyngs** [comment]
This is unsupported. Not going to fix unless you submit a PR.
