### ISSUE TITLE
1.20.6 but not support org.bukkit.inventory.meta.ItemMeta.getTool()

### ISSUE THREAD

**Issue by itorz7** [InfernalSuite/AdvancedSlimePaper#132]
**Describe the issue**

**Spigot version**
[16:07:10 INFO]: This server is running AdvancedSlimePaper version 1.20.6-16043-main@c8a935a (2024-06-11T19:12:04Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

**Plugin version**
[16:07:26 INFO]: SlimeWorldManager version 2.10.0
[16:07:26 INFO]: Advanced Slime World Manager is a resource that implements the Slime Region Format, designed by the Hypixel Team to load and save worlds more efficiently.
[16:07:26 INFO]: Authors: Grinderwolf, Paul19988, Jools, SoapTurtle, Gerolmed, b0ykoe, Owen and ComputerNerd100

**How to reproduce**

just use org.bukkit.inventory.meta.ItemMeta.getTool()

i try in papermc 1.20.6 getTool() is working but ASPAPER it not :(
![image](https://github.com/user-attachments/assets/db24bd41-8bf5-4557-af05-1fb0740652b6)

**Crash reports (if available)**
[16:06:08 ERROR]: Could not pass event PlayerGameModeChangeEvent to TestPlugin v1.0
java.lang.NoSuchMethodError: 'org.bukkit.inventory.meta.components.ToolComponent org.bukkit.inventory.meta.ItemMeta.getTool()'
        at TestPlugin-1.0-1725007083190.jar/me.dog.test.General.GameModeChange(General.java:59) ~[TestPlugin-1.0-1725007083190.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor84.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[slimeworldmanager-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[slimeworldmanager-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-16043-c8a935a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[slimeworldmanager-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[slimeworldmanager-1.20.6.jar:1.20.6-16043-c8a935a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[slimeworldmanager-1.20.6.jar:1.20.6-16043-c8a935a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[slimeworldmanager-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.changeGameModeForPlayer(ServerPlayerGameMode.java:89) ~[slimeworldmanager-1.20.6.jar:1.20.6-16043-c8a935a]
        at net.minecraft.server.level.ServerPlayer.setGameMode(ServerPlayer.java:2145) ~[slimeworldmanager-1.20.6.jar:1.20.6-16043-c8a935a]
        at org.bukkit.craftbukkit.entity.CraftPlayer.setGameMode(CraftPlayer.java:1825) ~[slimeworldmanager-1.20.6.jar:1.20.6-16043-c8a935a]
        at TestPlugin-1.0-1725007083190.jar/me.dog.test.paper.Helper.Commands.ChangeGamemodes.onCommand(ChangeGamemodes.java:32) ~[TestPlugin-1.0-1725007083190.jar:?]

**Comment by kyngs** [comment]
Can you verify on the latest ASP version? ASP does not touch anything regarding this.

**Comment by kyngs** [comment]
stale
