### ISSUE TITLE
Conflict with PacketEvents

### ISSUE THREAD

**Issue by karu724** [InfernalSuite/AdvancedSlimePaper#139]
**Describe the issue**
Traceback occurred when entity has summoned.
**Spigot version**
AdvancedSlimePaper 1.20.4 latest

**Plugin version**
1.20.4

**How to reproduce**
Same with description of the issue

**Crash reports (if available)**
[23:39:29] [Server thread/INFO]: Error while executing task on main thread
[23:39:29] [Server thread/WARN]: java.lang.IllegalStateException: PacketEvents failed to find a EntityLookup indexed 0 by its type in the com.infernalsuite.aswm.level.SlimeLevelInstance class!
[23:39:29] [Server thread/WARN]: at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.util.reflection.ReflectionObject.getField(Unknown Source)
[23:39:29] [Server thread/WARN]: at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.util.reflection.ReflectionObject.read(Unknown Source)
[23:39:29] [Server thread/WARN]: at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.util.reflection.ReflectionObject.readObject(Unknown Source)
[23:39:29] [Server thread/WARN]: at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.io.github.retrooper.packetevents.util.SpigotReflectionUtil.getEntityByIdWithWorldUnsafe(Unknown Source)
[23:39:29] [Server thread/WARN]: at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.io.github.retrooper.packetevents.util.SpigotReflectionUtil.getEntityById(Unknown Source)
[23:39:29] [Server thread/WARN]: at Matrix_7.9.22A.jar//me.rerere.matrix.thirdparty.io.github.retrooper.packetevents.util.SpigotConversionUtil.getEntityById(Unknown Source)
[23:39:29] [Server thread/WARN]: at Matrix_7.9.22A.jar//me.rerere.matrix..xj.u(Unknown Source)
[23:39:29] [Server thread/WARN]: at Matrix_7.9.22A.jar//me.rerere.matrix.misc.compatibility.Mainthread.executeOnEventLoop$lambda$6(Unknown Source)
[23:39:29] [Server thread/WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:39:29] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[23:39:29] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[23:39:29] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1469)
[23:39:29] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[23:39:29] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[23:39:29] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1446)
[23:39:29] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1369)
[23:39:29] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[23:39:29] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1347)
[23:39:29] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1236)
[23:39:29] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:39:29] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by davidmayr** [comment]
According to the stack trace, that's a thing PacketEvents needs to fix and not ASP

**Comment by kyngs** [comment]
We usually don't add support for hacky NMS plugins. We don't change any core mechanics/Bukkit API so this isn't our issue.
If this still occurs, try contacting them.
