### ISSUE TITLE
Can't connect to MongoDB without using `mongodb.uri`

### ISSUE THREAD

**Issue by HappyAreaBean** [InfernalSuite/AdvancedSlimePaper#142]
**Describe the issue**
When configured MongoDB without the uri, it will throw a `The connection string is invalid. Connection strings must start with either 'mongodb://' or 'mongodb+srv://` error.

<details><summary>Error Log</summary>
<p>

```log
[01:31:49 INFO]: [SlimeWorldPlugin] Loading server plugin SlimeWorldPlugin v3.0.0
[01:31:49 ERROR]: [SlimeWorldPlugin] Error initializing plugin 'plugin-3.0.0.jar' in folder 'plugins' (Is it up to date?)
java.lang.IllegalArgumentException: The connection string is invalid. Connection strings must start with either 'mongodb://' or 'mongodb+srv://
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.mongodb.ConnectionString.<init>(ConnectionString.java:361) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.mongodb.ConnectionString.<init>(ConnectionString.java:342) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.mongodb.client.MongoClients.create(MongoClients.java:61) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.infernalsuite.aswm.loaders.mongo.MongoLoader.<init>(MongoLoader.java:41) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.infernalsuite.aswm.plugin.loader.LoaderManager.<init>(LoaderManager.java:64) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.infernalsuite.aswm.plugin.SWPlugin.onLoad(SWPlugin.java:49) ~[plugin-3.0.0.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:48) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:548) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

</p>
</details> 

<details><summary>Full Server Log</summary>
<p>

```log
Starting org.bukkit.craftbukkit.Main
[01:31:36 INFO]: [bootstrap] Running Java 21 (OpenJDK 64-Bit Server VM 21.0.4+7-LTS; Eclipse Adoptium Temurin-21.0.4+7) on Windows 11 10.0 (amd64)
[01:31:36 INFO]: [bootstrap] Loading AdvancedSlimePaper 1.21.1-16392-paper_upstream@ba950ec (2024-10-21T16:24:13Z) for Minecraft 1.21.1
[01:31:38 INFO]: [PluginInitializerManager] Initializing plugins...
[01:31:38 INFO]: [PluginInitializerManager] Initialized 1 plugin
[01:31:38 INFO]: [PluginInitializerManager] Paper plugins (1):
 - SlimeWorldPlugin (3.0.0)
[01:31:44 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[01:31:46 INFO]: Loaded 1290 recipes
[01:31:46 INFO]: Loaded 1399 advancements
[01:31:47 INFO]: Starting minecraft server version 1.21.1
[01:31:47 INFO]: Loading properties
[01:31:47 INFO]: This server is running AdvancedSlimePaper version 1.21.1-16392-paper_upstream@ba950ec (2024-10-21T16:24:13Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
[01:31:48 INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
[01:31:48 INFO]: Server Ping Player Sample Count: 12
[01:31:48 INFO]: Using 4 threads for Netty based IO
[01:31:49 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and population gen parallelism of 2 threads
[01:31:49 INFO]: Default game type: SURVIVAL
[01:31:49 INFO]: Generating keypair
[01:31:49 INFO]: Starting Minecraft server on *:25565
[01:31:49 INFO]: Using default channel type
[01:31:49 INFO]: Paper: Using Java compression from Velocity.
[01:31:49 INFO]: Paper: Using Java cipher from Velocity.
[01:31:49 INFO]: [SlimeWorldPlugin] Loading server plugin SlimeWorldPlugin v3.0.0
[01:31:49 ERROR]: [SlimeWorldPlugin] Error initializing plugin 'plugin-3.0.0.jar' in folder 'plugins' (Is it up to date?)
java.lang.IllegalArgumentException: The connection string is invalid. Connection strings must start with either 'mongodb://' or 'mongodb+srv://
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.mongodb.ConnectionString.<init>(ConnectionString.java:361) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.mongodb.ConnectionString.<init>(ConnectionString.java:342) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.grinderwolf.swm.internal.mongodb.client.MongoClients.create(MongoClients.java:61) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.infernalsuite.aswm.loaders.mongo.MongoLoader.<init>(MongoLoader.java:41) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.infernalsuite.aswm.plugin.loader.LoaderManager.<init>(LoaderManager.java:64) ~[plugin-3.0.0.jar:?]
        at plugin-3.0.0.jar/com.infernalsuite.aswm.plugin.SWPlugin.onLoad(SWPlugin.java:49) ~[plugin-3.0.0.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:48) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:548) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:31:49 INFO]: Server permissions file permissions.yml is empty, ignoring it
[01:31:49 INFO]: Preparing level "world"
[01:31:50 INFO]: Preparing start region for dimension minecraft:overworld
[01:31:51 INFO]: Time elapsed: 1236 ms
[01:31:51 INFO]: Preparing start region for dimension minecraft:the_nether
[01:31:51 INFO]: Time elapsed: 151 ms
[01:31:51 INFO]: Preparing start region for dimension minecraft:the_end
[01:31:51 INFO]: Time elapsed: 116 ms
[01:31:51 INFO]: [SlimeWorldPlugin] Enabling SlimeWorldPlugin v3.0.0
[01:31:52 INFO]: [spark] Starting background profiler...
[01:31:52 INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.
[01:31:52 INFO]: Done preparing level "world" (2.799s)
[01:31:52 INFO]: Running delayed init tasks
[01:31:52 INFO]: Done (17.515s)! For help, type "help"
[01:31:52 INFO]: Timings Reset
```

</p>
</details> 

**Spigot version**
1.21.1-16392-paper_upstream@ba950ec

**Plugin version**
3.0.0

**How to reproduce**
1. Enable MongoDB and configure them without using `uri` in `sources.yml`
2. Start the server

**Crash reports (if available)**

**Comment by kyngs** [comment]
@HappyAreaBean Can you please verify that this still happens on the last develop build?

**Comment by HappyAreaBean** [comment]
Yes, I can confirm that the issue has been fixed in the latest develop build. :)
