### ISSUE TITLE
Cannot load craftplayer nms by using paper nms

### ISSUE THREAD

**Issue by karu724** [InfernalSuite/AdvancedSlimePaper#143]
**Describe the issue**
below logs

**Spigot version**
advanced slime paper 1.20.4 latest

**Plugin version**
slime world manager with advanced slime paper 1.20.4 latest releases

**How to reproduce**
By importing 

**Crash reports (if available)**
[02:16:25 ERROR]: Could not pass event EntityDamageByEntityEvent to MFMain v1.0-SNAPSHOT
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R4/entity/CraftPlayer
        at kr.myowall.MFMain.Model.PvPMatch.<init>(PvPMatch.java:39) ~[MFMain-1.0-SNAPSHOT.jar:?]
        at kr.myowall.MFMain.Managers.PvPManager.startMatch(PvPManager.java:661) ~[MFMain-1.0-SNAPSHOT.jar:?]
        at kr.myowall.MFMain.Managers.PvPManager.handlePvPAccept(PvPManager.java:497) ~[MFMain-1.0-SNAPSHOT.jar:?]
        at kr.myowall.MFMain.Managers.PvPManager.onEntityDamage(PvPManager.java:460) ~[MFMain-1.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor172.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:git-SlimeWorldManager-15981]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:265) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1252) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1107) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1051) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1286) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2221) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1059) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1471) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:966) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1135) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1319) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2283) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2769) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2693) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1469) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1446) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R4.entity.CraftPlayer
        ... 43 more

**Comment by kyngs** [comment]
See above ^
