### ISSUE TITLE
CRASH Failing to save a slime world after being converted

### ISSUE THREAD

**Issue by scipio3000** [InfernalSuite/AdvancedSlimePaper#20]
**Describe the issue**
Loaded a 1.17.1 slime world with entities, and unloaded it.

**Spigot version**
Latest paperclip of ASP

**Plugin version**
Latest

**How to reproduce**

**Crash reports (if available)**
```
Caused by: java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Byte (java.lang.Float and java.lang.Byte are in module java.base of loader 'bootstrap')
  at net.minecraft.world.entity.Mob.isLeftHanded(Mob.java:1586) ~[?:?]
  at net.minecraft.world.entity.Mob.addAdditionalSaveData(Mob.java:515) ~[?:?]
  at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2249) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at net.minecraft.world.entity.Entity.saveAsPassenger(Entity.java:2134) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at net.minecraft.world.entity.Entity.save(Entity.java:2150) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at com.infernalsuite.aswm.level.NMSSlimeChunk.getEntities(NMSSlimeChunk.java:172) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at com.infernalsuite.aswm.level.SlimeInMemoryWorld.unload(SlimeInMemoryWorld.java:109) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at com.infernalsuite.aswm.level.SlimeChunkLevel.unloadCallback(SlimeChunkLevel.java:25) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at net.minecraft.world.level.chunk.LevelChunk.onChunkUnload(LevelChunk.java:878) ~[?:?]
  at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1356) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1051) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1035) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:920) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:547) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-30]
  at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:69) ~[?:?]
  at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:646) ~[?:?]
  at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:701) ~[?:?]

```

**Comment by Owen1212055** [comment]
Because of the poor handling of legacy conversions in the past, I will most likely ignore invalid entities and log an error.

**Comment by scipio3000** [comment]
Thanks, that would be highly appreciated

**Comment by Owen1212055** [comment]
Fixed in https://github.com/InfernalSuite/AdvancedSlimePaper/commit/cb80fd4ed3e01514f59beaaf17045d3e50d2b260
