### ISSUE TITLE
NPE crash

### ISSUE THREAD

**Issue by korallo159** [InfernalSuite/AdvancedSlimePaper#30]
**Describe the issue**
Server was crashed during save.

**Spigot version**
Latest

**Plugin version**
Latest
**How to reproduce**
---

**Crash reports (if available)**
`[08:42:47 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.Chunk.getChunkHolder()" because "this.chunk" is null
        at com.infernalsuite.aswm.level.NMSSlimeChunk.getEntities(NMSSlimeChunk.java:168) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-36]
        at com.infernalsuite.aswm.level.SlimeInMemoryWorld.getForSerialization(SlimeInMemoryWorld.java:224) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-36]
        at com.infernalsuite.aswm.level.SlimeLevelInstance.save(SlimeLevelInstance.java:150) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-36]
        at com.infernalsuite.aswm.level.SlimeLevelInstance.saveIncrementally(SlimeLevelInstance.java:139) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-36]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1449) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-36]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-36]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-36]
        at net.minecraft.server.MinecraftServer$$Lambda$4612/0x00000000467f32c8.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]`

**Comment by korallo159** [comment]
May be related with: https://github.com/InfernalSuite/AdvancedSlimePaper/pull/26

**Comment by korallo159** [comment]
Please see PR
https://github.com/InfernalSuite/AdvancedSlimePaper/pull/31

**Comment by korallo159** [comment]
fixed with https://github.com/InfernalSuite/AdvancedSlimePaper/pull/31
