### ISSUE TITLE
Process lock problem on Windows machines

### ISSUE THREAD

**Issue by Syrent** [InfernalSuite/AdvancedSlimePaper#46]
**Describe the issue**
When attempting to clone a world on a Windows server, a `FileSystemException` and `IOException` exception is thrown due to Windows file lock limitations. While it is not ideal to use Windows for a Minecraft or any type of server, I tested the code on my local machine and it's inconvenient to upload plugins to the server every time I want to test them. Additionally, some users still use plugins on Windows servers.

**Spigot version**
SlimeWorldManager version git-SlimeWorldManager-61 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: e19b8ff)

**Plugin version**
Latest plugin-1.19.3-R0.1-SNAPSHOT.jar (2.10.0)

**How to reproduce**
1. Create an SlimeWorld `SWM.instance.createEmptyWorld(SWM.loader, arenaWorldName, false, slimeProperties)`
2. Load world
3. Get world `Bukkit.getWorld(templateSlimeWorld!!.name)!!`
4. Make some changes to world
5. Unload world using Bukkit API `Bukkit.unloadWorld(world, true)`
6. Clone world `templateSlimeWorld!!.clone(arenaWorldName)`
7. Delete the clonned world `Bukkit.unloadWorld(arena.world, false)` and `SWM.loader.deleteWorld(worldName)`

**Crash reports (if available)**
```
[07:40:04 INFO]: [SlimeWorldManager] [STDOUT] Deleting world.. eggwars_arena_test3_1.
[07:40:04 WARN]: java.io.IOException: Cannot delete file: slime_worlds\eggwars_arena_test3_1.slime
[07:40:04 WARN]:        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1344)
[07:40:04 WARN]:        at plugin-1.19.3-R0.1-SNAPSHOT (2).jar//com.grinderwolf.swm.plugin.loaders.file.FileLoader.deleteWorld(FileLoader.java:147)
[07:40:04 WARN]:        at SayanEggwars.jar//me.sayandevelopment.sayaneggwars.arena.EWArena$Companion$Template.deleteGeneratedArena(EWArena.kt:663)
[07:40:04 WARN]:        at SayanEggwars.jar//me.sayandevelopment.sayaneggwars.arena.EWArena.finish(EWArena.kt:326)
[07:40:04 WARN]:        at SayanEggwars.jar//me.sayandevelopment.sayaneggwars.arena.EWArena.terminate(EWArena.kt:242)
[07:40:04 WARN]:        at SayanEggwars.jar//me.sayandevelopment.sayaneggwars.test.DebugCommand.onCommand(DebugCommand.kt:54)
[07:40:04 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[07:40:04 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[07:40:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929)
[07:40:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[07:40:04 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[07:40:04 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:313)
[07:40:04 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:297)
[07:40:04 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[07:40:04 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[07:40:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[07:40:04 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[07:40:04 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[07:40:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[07:40:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[07:40:04 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1356)
[07:40:04 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[07:40:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[07:40:04 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1333)
[07:40:04 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1326)
[07:40:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[07:40:04 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1304)
[07:40:04 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[07:40:04 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[07:40:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:40:04 WARN]: Caused by: java.nio.file.FileSystemException: slime_worlds\eggwars_arena_test3_1.slime: The process cannot access the file because it is being used by another process
[07:40:04 WARN]:        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[07:40:04 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[07:40:04 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[07:40:04 WARN]:        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[07:40:04 WARN]:        at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
[07:40:04 WARN]:        at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
[07:40:04 WARN]:        at org.apache.commons.io.file.PathUtils.deleteFile(PathUtils.java:487)
[07:40:04 WARN]:        at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:392)
[07:40:04 WARN]:        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1341)
[07:40:04 WARN]:        ... 29 more
```

**Comment by kyngs** [comment]
This should be fixed by https://github.com/InfernalSuite/AdvancedSlimePaper/commit/a339b6b3192b135c532ba8c7682adb4b199bbf05.
I don't have a Windows machine, so I cannot check whether the fix works, but I think it does.
In case it does not, please reopen this issue!
